services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - database
    ports:
      - 3333:3333
    volumes:
      - .:/app
    env_file: .env.development
    container_name: apphold
    entrypoint: sh ./entrypoints/app-entrypoint.sh

  database:
    extends:
      file: docker-compose.base.yml
      service: database_development

volumes:
  pgdata:
    driver: local
