services:
  test:
    build:
      context: .
      dockerfile: Dockerfile.test
    container_name: apphold_test
    depends_on:
      - database
    env_file: .env.test
    ports:
      - 3333:3333
    volumes:
      - .:/usr/app

  database:
    extends:
      file: docker-compose.base.yml
      service: database_test

volumes:
  pgdata:
    driver: local
