services:
  database_development:
    image: postgres
    container_name: database_apphold
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: apphold_development
    volumes:
      - pgdata:/data/postgres

  database_test:
    image: postgres
    container_name: database_apphold
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: apphold_test
    volumes:
      - pgdata:/data/postgres

volumes:
  pgdata:
    driver: local
