services:
  database_apphold:
    image: postgres
    container_name: database_apphold
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=apphold
    volumes:
      - pgdata:/data/posgres

  app:
    build: .
    container_name: apphold
    ports:
      - 3333:3333
    volumes:
      - .:/usr/app

volumes:
  pgdata:
    driver: local
