-- AlterTable
ALTER TABLE "Asset" ALTER COLUMN "last_12_months_dividends" DROP NOT NULL;
ALTER TABLE "Asset" ALTER COLUMN "zip" DROP NOT NULL;
ALTER TABLE "Asset" ALTER COLUMN "employees" DROP NOT NULL;
ALTER TABLE "Asset" ALTER COLUMN "total_stocks" DROP NOT NULL;
ALTER TABLE "Asset" ALTER COLUMN "ceo" DROP NOT NULL;
ALTER TABLE "Asset" ALTER COLUMN "state" DROP NOT NULL;
ALTER TABLE "Asset" ALTER COLUMN "website" DROP NOT NULL;

ALTER TABLE "AssetData" ALTER COLUMN "revenue" DROP NOT NULL;
ALTER TABLE "AssetData" ALTER COLUMN "net_income" DROP NOT NULL;
ALTER TABLE "AssetData" ALTER COLUMN "dividends_paid" DROP NOT NULL;
ALTER TABLE "AssetData" ALTER COLUMN "fco" DROP NOT NULL;
ALTER TABLE "AssetData" ALTER COLUMN "fcf" DROP NOT NULL;
ALTER TABLE "AssetData" ALTER COLUMN "ebit" DROP NOT NULL;
ALTER TABLE "AssetData" ALTER COLUMN "cash" DROP NOT NULL;
ALTER TABLE "AssetData" ALTER COLUMN "equity" DROP NOT NULL;
ALTER TABLE "AssetData" ALTER COLUMN "net_margin" DROP NOT NULL;
ALTER TABLE "AssetData" ALTER COLUMN "roe" DROP NOT NULL;
ALTER TABLE "AssetData" ALTER COLUMN "payout" DROP NOT NULL;
